### ISSUE TITLE
glibc issue with itch.io build

### ISSUE THREAD

**Issue by geotre** [liquid600pgm/memrecall#3]
The game works when I compile from the github repo, but I get this error when running the itch build:
`./memrecall: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by ./memrecall)`
(ubuntu 18.04)

**Comment by liquidev** [comment]
This is to be expected, I built the game using a newer glibc on Fedora 30. I can't do anything about it now, the game fails to build on my Ubuntu 16.04 VM.

**Comment by liquidev** [comment]
Update: My friend sent me this: https://github.com/wheybags/glibc_version_header
I'll try compiling with this today and report back on that.

Edit: oh shit, I just looked at the main page of this repo and apparently the game's now written in C++.

**Comment by liquidev** [comment]
@geotre Please try running the game again, this should be resolved. https://lqdev.itch.io/memrecall

**Comment by geotre** [comment]
I can confirm this now works!

**Comment by liquidev** [comment]
Glad to hear that!
