### ISSUE TITLE
nimble install task is missing a step

### ISSUE THREAD

**Issue by rayman22201** [liquid600pgm/memrecall#4]
I'm not sure if this is a bug with nimble, glfw, rapid, or your game 😕 

Basically, you need to update your nimble install task to do a `git fetch` before doing the `git checkout #latest`.
Depending on the git version (Windows in particular ends up with weird older git versions) the fetch will not happen automatically.

When I tried to nimble install I get this:
```
        ... C:\Users\ray\.choosenim\toolchains\nim-#devel\lib\system\fatal.nim(39, 5) Error: unhandled exception: git.nim(25, 12) `ret == 0` Command failed: (1, false)
        ... ccmd: cmd /c cd C:\Users\ray\.nimble\pkgs\rapid-0.1.0\rapid\lib\glfw_src && git checkout #latest
        ... result:
        ... error: pathspec '#latest' did not match any file(s) known to git.
        ...  [AssertionError]
```

If I manually do:
```
cd C:\Users\ray\.nimble\pkgs\rapid-0.1.0\rapid\lib\glfw_src
git fetch
```
nimble install then works.

**Comment by liquidev** [comment]
This is an issue with nimterop, unfortunately it's out of my control. Sorry.

For some reason, this only happens the first time you compile, so trying again is the only solution I know so far. I'll include your suggestion in the rapid readme.
