### ISSUE TITLE
OpenGL failure

### ISSUE THREAD

**Issue by rayman22201** [liquid600pgm/memrecall#5]
😿 Attempting to run the game gives me:
```
err: ARB_direct_state_access is not available. Please update your graphics drivers
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

I'm on a Windows 10 laptop with a Nvidia Quadro M100M graphics card, with the latest drivers. 

Edit: No I'm not. Windows is falling back to the embedded Intel Drivers :/
Detailed OpenGL output is here: https://gist.github.com/rayman22201/e76535c6c8ca2950aa7aa0c81870f7aa

liquid600gpm is already fixing this. We have been talking directly on IRC. I'm just putting these notes here for posterity. (In case anyone else runs into something similar.)
https://irclogs.nim-lang.org/02-10-2019.html#19:32:30

**Comment by liquidev** [comment]
Fixed in rapid.
